### ISSUE TITLE
Safari Strict Mode implementation and route._state

### ISSUE THREAD

**Issue by there4** [tbranyen/backbone.routemanager#10]
It appears that some versions of Safari are having trouble with [line 95](https://github.com/tbranyen/backbone.routemanager/blob/master/backbone.routemanager.js#L95). It seems that it's throwing an error when setting that property on a string.

I'm considering branching this repo for a fix, but I was curious what the original intent of the `_state` was, I don't see it in use elsewhere in the code. Is it something can be discarded, or did you have plans for it?

**Comment by tbranyen** [comment]
Landed in master via PR
